#######################################################
# 
# AccountBuilder.py
# Python implementation of the Class AccountBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Account

class AccountBuilder:
    def AccountBuilder(currency):
        pass

    def Build():
        pass