#######################################################
# 
# AccountBuilder.py
# Python implementation of the Class AccountBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Account
from Shared.Enums.Currency import Currency

class AccountBuilder():
    def __init__(
        self,
        currency: Currency) -> None:
        self.currency = currency

    def Build(self)-> Account.Account:
        return Account.Account(self.currency)