#######################################################
# 
# AdminBuilder.py
# Python implementation of the Class AdminBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import IUser
import Certificate
import UserBuilder

class AdminBuilder(UserBuilder):
    def AdminBuilder(billingAddress, birthDate, email, fullName, gender, jmbg, password, username):
        pass

    def Build():
        pass

    def BuildCertificate():
        pass

    def BuildUser():
        pass