#######################################################
# 
# CardBuilder.py
# Python implementation of the Class CardBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from Card import (
    Card
)
from CardCreateInfo import(
    CardCreateInfo
)


class CardBuilder:
    def __init__(
        self,
        cardInfo: CardCreateInfo) -> None:
        self.cardInfo = cardInfo

    def Build(self)-> Card:
        return Card(
            self.cardInfo.cardHolder,
            self.cardInfo.cardType,
            self.cardInfo.cardProcessor
        )