#######################################################
# 
# CardBuilder.py
# Python implementation of the Class CardBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Card
import CardCreateInfo

class CardBuilder:
    def Build():
        pass

    def CardBuilder(cardInfo):
        pass