#######################################################
# 
# ClientBuilder.py
# Python implementation of the Class ClientBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import IUser
import Certificate
import AccountBuilder
import CardBuilder
import UserBuilder

class ClientBuilder(UserBuilder):
    accountBuilder= AccountBuilder()

    cardBuilder= CardBuilder()

    def Build():
        pass

    def BuildAccounts():
        pass

    def BuildCards():
        pass

    def BuildCertificate():
        pass

    def BuildUser():
        pass

    def ClientBuilder(billingAddress, birthDate, email, fullName, gender, jmbg, password, username, cardsInfo, accountInfo):
        pass