#######################################################
# 
# ClientBuilder.py
# Python implementation of the Class ClientBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from Account import Account
from CardCreateInfo import CardCreateInfo
import IUser
from Certificate import Certificate
import AccountBuilder
from CardBuilder import CardBuilder
from Shared.Enums.Currency import Currency
import UserBuilder
from Shared.Enums.Gender import (
    Gender
)
from Shared.Enums.UserType import (
    UserType
)
from datetime import date
from Client import (
    Client
)
from AccountBuilder import AccountBuilder

class ClientBuilder(UserBuilder):
    def __init__(
        self,
        billingAddress: str,
        birthDate: date,
        email: str,
        fullName: str,
        gender: Gender,
        jmbg: int,
        username: str,
        password: str,
        id: int = None, 
        certificate: Certificate = None,
        accountsInfo: list[Currency] = [],
        cardsInfo: dict[Currency, list[CardCreateInfo]] = {}) -> None:
        
        UserBuilder.__init__(self,
            UserType.CLIENT,
            billingAddress, 
            birthDate,
            email,
            fullName, 
            gender,
            jmbg,
            username,
            password,
            id, 
            certificate
        )
        self.accountsInfo = accountsInfo
        self.cardsInfo = cardsInfo

    def Build()-> Client:
        pass

    def BuildAccounts(self)-> list[Account]:
        self.accounts = list[Account]
        for ai in self.accountsInfo:

            accBuilder = AccountBuilder(ai)
            acc = accBuilder.Build()
            self.BuildCards(acc, self.cardsInfo[ai])


    def BuildCards(self, account: Account, cardsInfo: list[CardCreateInfo]):
        for ci in cardsInfo:
            cardBuilder = CardBuilder(ci)
            account.cards.append(cardBuilder.Build())

    def BuildCertificate(self):
        