#######################################################
# 
# UserBuilder.py
# Python implementation of the Class UserBuilder
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import IUser
import Certificate

class UserBuilder:
    def Build():
        pass

    def BuildCertificate():
        pass

    def BuildUser():
        pass

    def UserBuilder(billingAddress, birthDate, email, fullName, gender, jmbg, password, username):
        pass