#######################################################
# 
# Account.py
# Python implementation of the Class Account
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Card
import Transaction
import IAccountReport

class Account:
    cards= Card()

    transactions= Transaction()

    report= IAccountReport()

    def GetFileReport(startDate = None, endDate = None):
        pass

    def GetTextReport(startDate = None, endDate = None):
        pass