#######################################################
# 
# AccountManager.py
# Python implementation of the Class AccountManager
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import CardCreateInfo
import Transaction
import TransactionClientInfo
import Account

class AccountManager:
    accounts= Account()

    def AddAccount(currency):
        pass

    def AddCard(cardInfo, accountNumber):
        pass

    def ExchangeMoney(currencyFrom, currencyTo, amount):
        pass

    def GetAccountFileReport(dateFrom = None, dateTo = None, accountNumber):
        pass

    def GetAccountTextReport(dateFrom = None, dateTo = None, accountNumber):
        pass

    def GetTransactionFileReport(id):
        pass

    def TransferMoney(transaction, fromAccountNumber, toAccount, clientInfo):
        pass