#######################################################
# 
# CardCreateInfo.py
# Python implementation of the Class CardCreateInfo
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################


class CardCreateInfo:
    pass