#######################################################
# 
# Card.py
# Python implementation of the Class Card
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from Enums import (
    CardType,
    CreditCardProcessor
)

from SharedMethods import (
    BankNumbers
)

class Card():
    def __init__(
        self,
        cardHolder: str,
        cardType: CardType,
        cardProcessor: CreditCardProcessor
    ) -> None:
        self.cardHolder = cardHolder
        self.cardNumber = BankNumbers.BankNumbers.GenerateCardNumber()
        self.cardType = cardType
        self.cvc = BankNumbers.BankNumbers.GenerateCVC()
        self.pin = BankNumbers.BankNumbers.GeneratePIN()
        self.cardProcessor = cardProcessor
