#######################################################
# 
# CSVTransactionReport.py
# Python implementation of the Class CSVTransactionReport
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Transaction
import ITransactionReport

class CSVTransactionReport(ITransactionReport):
    def WriteReportText(transaction):
        pass

    def WriteReportToFile(transaction):
        pass