#######################################################
# 
# IAccountReport.py
# Python implementation of the Interface IAccountReport
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Account

class IAccountReport:
    def WriteReportText(account):
        pass

    def WriteReportToFile(account):
        pass