#######################################################
# 
# Transaction.py
# Python implementation of the Class Transaction
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Account
import ITransactionReport

class Transaction:
    report= ITransactionReport()

    def GetFileReport():
        pass

    def GetTextReport():
        pass