#######################################################
# 
# Transaction.py
# Python implementation of the Class Transaction
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from TransactionClientInfo import *
from TransactionAccountInfo import *
from datetime import datetime
from Shared.BankConfig import BankConfigParser
import os


class Transaction():
    def __init__(
        self,
        accountFrom: TransactionAccountFromInfo,
        accountTo: TransactionAccountToInfo,
        amount: float,
        id: int,
        modelCode: int,
        paymentCode: tuple[int, str],
        paymentPurpose: str,
        referenceNumber: str
        ) -> None:
        self.preciseTime = datetime.today()
        config = BankConfigParser()
        self.provision = config.ProvisionPercentage * amount
        self.accountFrom = accountFrom
        self.accountTo = accountTo
        self.amount = amount
        self.id = id
        self.modelCode = modelCode
        self.paymentCode = paymentCode
        self.paymentPurpose = paymentPurpose
        self.referenceNumber = referenceNumber

    def GetFileReport(self)-> str:
        """
            Returns file path of report
        """
        text = self.GetTextReport()
        dateStr = self.preciseTime.strftime("%Y%m%d-%H%M%S")

        _path = os.path.join(
            os.getcwd(), "Reports", f"""{self.id} on {dateStr}.csv"""
        )

        f = open(_path, "w")
        f.write(text)
        f.close()

        return _path

    def GetTextReport(self)-> str:
        """
            Returns text report
        """
        return f"""
Id, {self.id}
# Account FROM information
Account number, {self.accountFrom.accountNumber}
Client name, {self.accountFrom.clientInfo.fullName}
Client address, {self.accountFrom.clientInfo.billingAddress}
Balance before, {self.accountFrom.balanceBefore}
Balance after, {self.accountFrom.balanceAfter}
Currency used, {Currency(self.accountFrom.currency).name}

# Account TO information
Account number, {self.accountTo.accountNumber}
Client name, {self.accountTo.clientInfo.fullName}
Client address, {self.accountTo.clientInfo.billingAddress}

# Transaction information
Amount, {self.amount}
Provision paid, {self.provision}
Model code, {self.modelCode}
Payment Code, {self.paymentCode[0]} - {self.paymentCode[1]}
Payment Purpose, {self.paymentPurpose}
Precise Time, {self.preciseTime.isoformat()}
Reference number, {self.referenceNumber}
        """
