#######################################################
# 
# TransactionClientInfo.py
# Python implementation of the Class TransactionClientInfo
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################


class TransactionClientInfo:
    """Information about client for one transaction.
    """
    pass