# Generated by Django 3.2.9 on 2021-12-24 16:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import sbesbank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountBalance', models.FloatField()),
                ('accountNumber', models.CharField(max_length=24)),
                ('blocked', models.BooleanField(default=False)),
                ('currency', enumchoicefield.fields.EnumChoiceField(enum_class=sbesbank.models.Currency, max_length=3)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2021, 12, 24, 17, 14, 8, 775723))),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('currency', enumchoicefield.fields.EnumChoiceField(enum_class=sbesbank.models.Currency, max_length=3, primary_key=True, serialize=False, unique=True)),
                ('dateModified', models.DateField()),
                ('rateInDinar', models.FloatField()),
            ],
            options={
                'db_table': 'exchangerate',
            },
        ),
        migrations.CreateModel(
            name='IUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('billingAddress', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male')], max_length=20)),
                ('jmbg', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999), django.core.validators.MinValueValidator(10000000000000)])),
                ('birthDate', models.DateField()),
                ('userType', models.CharField(choices=[('admin', 'admin'), ('client', 'client')], max_length=40)),
            ],
            options={
                'db_table': 'iuser',
            },
        ),
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('code', models.PositiveSmallIntegerField(max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'paymentcode',
            },
        ),
        migrations.CreateModel(
            name='TrAcTransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=25)),
                ('billingAddress', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tractransferinfo',
            },
        ),
        migrations.CreateModel(
            name='TrMyAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceBefore', models.FloatField()),
                ('balanceAfter', models.FloatField()),
                ('accountNumber', models.CharField(max_length=25)),
                ('billingAddress', models.CharField(max_length=50)),
                ('fullName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'trmyaccountinfo',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('modelCode', models.IntegerField(blank=True, default=None, max_length=2, null=True)),
                ('paymentPurpose', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('preciseTime', models.DateTimeField(default=datetime.datetime(2021, 12, 24, 17, 14, 8, 777726))),
                ('provision', models.FloatField(null=True)),
                ('referenceNumber', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('transactionType', models.CharField(choices=[('INFLOW', 'INFLOW'), ('OUTFLOW', 'INFLOW')], max_length=30)),
                ('currency', enumchoicefield.fields.EnumChoiceField(enum_class=sbesbank.models.Currency, max_length=3)),
                ('myAccInfoFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbesbank.trmyaccountinfo')),
                ('paymentCodeFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbesbank.paymentcode')),
                ('transferAccInfoFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbesbank.tractransferinfo')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbesbank.iuser')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorityName', models.CharField(max_length=50)),
                ('pemPath', models.CharField(max_length=200, unique=True)),
                ('keyPath', models.CharField(max_length=200, unique=True)),
                ('certificateName', models.CharField(max_length=100, unique=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sbesbank.iuser', unique=True)),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardHolder', models.CharField(max_length=100)),
                ('cardNumber', models.CharField(max_length=20)),
                ('cvc', models.CharField(max_length=64)),
                ('pin', models.CharField(max_length=64)),
                ('cardProcessor', models.CharField(choices=[('VISA', 'VISA'), ('MASTER_CARD', 'MASTER_CARD'), ('AMERICAN_EXPRESS', 'AMERICAN_EXPRESS')], max_length=100)),
                ('cardType', models.CharField(choices=[('DINA', 'DINA'), ('CREDIT', 'CREDIT')], max_length=20)),
                ('validUntil', models.DateField()),
                ('accountFK', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbesbank.account')),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sbesbank.client'),
        ),
    ]
