#######################################################
# 
# CertificateGenerator.py
# Python implementation of the Class CertificateGenerator
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
import Certificate

class CertificateGenerator:
    def GenerateCertificate(
        certificateName: str,
        authorityName: str
        ) -> Certificate:
        pass