#######################################################
# 
# AccountManager.py
# Python implementation of the Class AccountManager
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from Builders.CardBuilder import CardBuilder
from CardCreateInfo import CardCreateInfo
from Shared.Enums.Currency import Currency
import Transaction
import TransactionClientInfo
from Account import Account

class AccountManager():
    def __init__(
        self,
        accounts: list[Account]
    ) -> None:
        self.accounts = accounts

    def AddAccount(self, currency: Currency)-> None:
        exists = False
        for a in self.accounts:
            if a.currency == currency:
                exists = True
                break
        
        if not exists:
            self.accounts.append(
                Account(currency)
            )
        else:
            raise Exception("Account with given currency already exists.")

    def AddCard(
        self,
        cardInfo: CardCreateInfo,
        accountNumber: str)-> None:
        
        for a in self.accounts:
            if a.accountNumber == accountNumber:
                if not (a.HasCard(cardInfo)):
                    cardBuilder = CardBuilder(cardInfo)
                    a.cards.append(cardBuilder.Build())
                    return
                else:
                    raise Exception(
                        "Chosen account already has card with given specifications."
                    )

        raise Exception(
            "No account found with given number."
        )

    def ExchangeMoney(currencyFrom, currencyTo, amount):
        pass

    def GetAccountFileReport(dateFrom = None, dateTo = None, accountNumber):
        pass

    def GetAccountTextReport(dateFrom = None, dateTo = None, accountNumber):
        pass

    def GetTransactionFileReport(id):
        pass

    def TransferMoney(transaction, fromAccountNumber, toAccount, clientInfo):
        pass