#######################################################
# 
# Admin.py
# Python implementation of the Class Admin
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from IUser import IUser
from Certificate import Certificate
from datetime import (
    date
)

from Shared.Enums import (
    Gender, UserType
)


class Admin(IUser):
    def __init__(
        self,
        billingAddress: str,
        birthDate: date,
        email: str,
        fullName: str,
        gender: Gender.Gender,
        jmbg: int,
        password: str,
        username: str,
        userType: UserType.UserType,
        id: int = None,
        certificate: Certificate = None) -> None:
        IUser.__init__(
            self,
            billingAddress,
            birthDate,
            email,
            fullName,
            gender,
            jmbg,
            password,
            username,
            userType,
            id,
            certificate
        )
        