#######################################################
# 
# CardCreateInfo.py
# Python implementation of the Class CardCreateInfo
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from Shared.Enums.CreditCardProcessor import (
    CreditCardProcessor
)
from Shared.Enums.CardType import (
    CardType
)


class CardCreateInfo():
    def __init__(
        self,
        cardHolder: str,
        cardProcessor: CreditCardProcessor,
        cardType: CardType) -> None:
        
        self.cardHolder = cardHolder
        self.cardProcessor = cardProcessor
        self.cardType = cardType