#######################################################
# 
# Card.py
# Python implementation of the Class Card
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from Shared.Enums import (
    CardType,
    CreditCardProcessor
)

from Shared.BankNumbers import (
    BankNumbers
)

class Card():
    def __init__(
        self,
        cardHolder: str,
        cardType: CardType,
        cardProcessor: CreditCardProcessor
    ) -> None:
        self.cardHolder = cardHolder
        self.cardProcessor = cardProcessor
        self.cardType = cardType
        self.cardNumber = BankNumbers.BankNumbers.GenerateCardNumber(
            self.cardProcessor
        )
        self.cvc = BankNumbers.BankNumbers.GenerateCVC()
