#######################################################
# 
# CSVAccountReport.py
# Python implementation of the Class CSVAccountReport
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from Account import Account
import IAccountReport

class CSVAccountReport(IAccountReport):
    

    def WriteReportText(account: Account)-> str:
        pass

    def WriteReportToFile(account: Account)-> str:
        pass