#######################################################
# 
# IUser.py
# Python implementation of the Class IUser
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from Certificate import Certificate
from datetime import (
    date
)

from Enums import (
    Gender, UserType
)


class IUser():
    def __init__(
        self,
        billingAddress: str,
        birthDate: date,
        email: str,
        fullName: str,
        gender: Gender.Gender,
        jmbg: int,
        password: str,
        username: str,
        userType: UserType.UserType,
        id: int = None,
        certificate: Certificate = None) -> None:

        self.billingAddress = billingAddress
        self.birthDate = birthDate
        self.email = email
        self.fullName = fullName
        self.gender = gender
        self.jmbg = jmbg
        self.password = password
        self.username = username
        self.userType = userType
        self.certificate = certificate

    def SetCertificate(self, certificate: Certificate):
        if certificate.ValidateCertificate():
            self.certificate = certificate
        else:
            raise Exception(
                'Trying to assign not valid certificate.'
            )
    