#######################################################
# 
# TransactionClientInfo.py
# Python implementation of the Class TransactionClientInfo
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################


class TransactionClientInfo():
    def __init__(
        self, 
        billingAddress: str,
        fullName: str
        ) -> None:
        
        self.billingAddress = billingAddress
        self.fullName = fullName