#######################################################
# 
# AccountType.py
# Python implementation of the Enumeration AccountType
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class AccountType(Enum):
    DOMESTIC = 0
    FOREIGN = 1