#######################################################
# 
# ClientType.py
# Python implementation of the Enumeration ClientType
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class ClientType(Enum):
    pass