#######################################################
# 
# CreditCardProcessor.py
# Python implementation of the Enumeration CreditCardProcessor
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum


class CreditCardProcessor(Enum):
    VISA = 0
    MASTER_CARD = 1
    AMERICAN_EXPRESS = 2