#######################################################
# 
# Currency.py
# Python implementation of the Enumeration Currency
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum


class Currency(Enum):
    USD = 0
    EUR = 1
    CHF = 2
    GBP = 3
    RUB = 4
    CNY = 5
    CAD = 6
    AUD = 7
    RSD = 8