#######################################################
# 
# Gender.py
# Python implementation of the Enumeration Gender
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class Gender(Enum):
    MALE = 0
    FEMALE = 1