#######################################################
# 
# UserType.py
# Python implementation of the Enumeration UserType
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class UserType(Enum):
    ADMIN = 0
    CLIENT = 1