#######################################################
# 
# CertificateGenerator.py
# Python implementation of the Class CertificateGenerator
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################
from sbesbank.models import Certificate


class CertificateGenerator:
    def GenerateCertificate(
            self,
            certificateName: str,
            authorityName: str
        ) -> Certificate:
        """
            Generating certificate for user.
            UserId must be set after generation
        """
        cert = Certificate()
        cert.authorityName = authorityName
        cert.certificateName = certificateName
        cert.cerPath = self.GenerateCerFile()
        cert.pvkPath = self.GeneratePvkFile()
        cert.pfxPath = self.GeneratePfxFile()

    def GenerateCerFile(self) -> str:
        """
            Returns path to certificate
        """
        return ""

    def GeneratePfxFile(self) -> str:
        """
            Returns path to certificate
        """
        return ""
    
    def GeneratePvkFile(self) -> str:
        """
            Returns path to certificate
        """
        return ""
