#######################################################
# 
# CardType.py
# Python implementation of the Enumeration CardType
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class CardType(Enum):
    DEBIT = 0
    CREDIT = 1

    def __str__(self) -> str:
        if(self.value == 0):
            return "DEBIT"
        elif(self.value):
            return "CREDIT"
        else:
            return "UNDEFINED CARD TYPE"

    def __int__(self) -> int:
        return int(self.value)

    def GetFromStr(value:str):
        if (value.strip().upper() == "DEBIT"):
            return CardType.DEBIT
        else:
            return CardType.CREDIT