#######################################################
# 
# CardType.py
# Python implementation of the Enumeration CardType
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum

class CardType(Enum):
    DEBIT = 0
    CREDIT = 0

    def __str__(self) -> str:
        return str(self.value)