#######################################################
# 
# CreditCardProcessor.py
# Python implementation of the Enumeration CreditCardProcessor
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum


class CreditCardProcessor(Enum):
    VISA = 0
    MASTER_CARD = 1
    AMERICAN_EXPRESS = 2

    def __str__(self) -> str:
        if(self.value == 0):
            return "VISA"
        elif(self.value == 1):
            return "MASTER_CARD"
        elif(self.value == 2):
            return "AMERICAN_EXPRESS"
        else:
            return "UNDEFINED CARD TYPE"

    def __int__(self) -> int:
        return int(self.value)

    def GetFromStr(value:str):
        if(value.strip().upper() == "VISA"):
            return CreditCardProcessor.VISA
        elif(value.strip().upper() == "MASTER_CARD"):
            return CreditCardProcessor.MASTER_CARD
        else:
            return CreditCardProcessor.AMERICAN_EXPRESS