#######################################################
# 
# Currency.py
# Python implementation of the Enumeration Currency
# Generated by Enterprise Architect
# Created on:      29-Nov-2021 6:55:28 PM
# Original author: acast
# 
#######################################################

from enum import Enum


class Currency(Enum):
    USD = 0
    EUR = 1
    CHF = 2
    GBP = 3
    RUB = 4
    CNY = 5
    CAD = 6
    AUD = 7
    RSD = 8

    def __str__(self) -> str:
        return str(self.value)
    
    def __int__(self) -> int:
        return int(self.value)

    def GetFromStr(value:str):
        if(value.strip().upper() == "USD"):
            return Currency.USD
        elif(value.strip().upper() == "EUR"):
            return Currency.EUR
        elif(value.strip().upper() == "CHF"):
            return Currency.CHF
        elif(value.strip().upper() == "GBP"):
            return Currency.GBP
        elif(value.strip().upper() == "RUB"):
            return Currency.RUB
        elif(value.strip().upper() == "CNY"):
            return Currency.CNY
        elif(value.strip().upper() == "CAD"):
            return Currency.CAD
        elif(value.strip().upper() == "AUD"):
            return Currency.AUD
        else:
            return Currency.RSD
        